# Nome da aplicação
spring:
  application:
    name: Book

  # URL de conexão com o banco de dados (Banco específico para o Book Service)
  datasource:
    url: jdbc:mysql://localhost:3306/book_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  # Configurações do Hibernate
  jpa:
    hibernate:
      ddl-auto: update

  # Configurar Jackson para não falhar em objetos vazios
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: NON_NULL

# Definir porta para 8100
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
