server:
  port: 8888
spring:
  application:
    name: alberto-conig-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marcosffp/alberto-conig-server
          default-label: main
          search-paths:
          - 'greeting-service*'